### ISSUE TITLE
"package.json" not found on declared modules

### ISSUE THREAD

**Issue by Kim-Andersen** [charliedowler/gulp-flowtype#40]
Hi there.
First of all, thanks for your contribution to the community.

The issue:
My setup: Using gulp I'm watching .js files and runs gulp-flowtype on any change. I'm ignoring node_modules and instead declaring required modules using the declarations option. This works fine except one thing: For each module I declare, gulp-flowtype prompts an error that it can't find the "package.json" file. Example error output:

Failure("internal error: package [app path]/node_modules/lodash/package.json not found")

Can you guide be towards a solution?

Thanks

**Comment by Kim-Andersen** [comment]
@charliedowler Why did you close this issue?

**Comment by charliedowler** [comment]
Hi,

I should've explained, I don't think it's gulp-flowtype causing the issue, if you've narrowed it down to gulp-flowtype could you send me the instructions to reproduce your issue.

Due to the lack of activity on the issue and the fact that gulp-flowtype doesn't use lodash directly I closed the issue.

I've just fixed a few issues and will be releasing version `5.0` soon, after it's released give it another go and check if it resolves your issue.

Cheers,
Charlie

**Comment by Kim-Andersen** [comment]
O, thanks, I will give your new version a try when its out.

**Comment by charliedowler** [comment]
@Kim-Andersen Just released `1.0.0` :+1:
